# Generated by Django 4.2.2 on 2023-07-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tel',
            field=models.CharField(max_length=30),
        ),
    ]
